model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct  
model_revision: main
torch_dtype: float32
attn_implementation: default
bf16: false
tf32: false

max_steps: 50
per_device_train_batch_size: 1  
gradient_accumulation_steps: 20  
learning_rate: 5.0e-6
lr_scheduler_type: cosine
warmup_ratio: 0.1

num_hidden_layers: 6
hidden_size: 512
num_attention_heads: 8
attention_probs_dropout_prob: 0.1
hidden_dropout_prob: 0.1
max_prompt_length: 96
max_completion_length: 96
num_generations: 1  
use_vllm: false  
vllm_gpu_memory_utilization: 0.5  

logging_strategy: no  
save_strategy: steps
save_steps: 100
  
max_grad_norm: 0.5
seed: 42
